import './globals.css';
import { Inter } from 'next/font/google';
import { ColorModeScript } from '@chakra-ui/react';
import theme from './theme';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      data-theme="dark"
      style={{ colorScheme: 'dark' }}
      suppressHydrationWarning
    >
      <body className={`${inter.className} chakra-ui-dark`}>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        {children}
      </body>
    </html>
  );
}
